### ISSUE TITLE
阿里国际UED前端团队招聘

### ISSUE THREAD

**Issue by zincli** [csbun/blog#1]
貌似你是UC的同事？有没有兴趣来国际UED团队换换口味，我们在深圳、杭州都有岗位。团队承接集团内部各种业务。深圳团队主要是负责交易、评价等一些基础业务。

我看了你的博客过来的，我近一段时间也折腾了不少karma和ci的事情，刚刚在搜怎么在多浏览器测试的情况下拿到coverage文件上传集团CISE的覆盖率服务。

**Comment by csbun** [comment]
我对 Karma 和 CI 了解也不深呢😁

**Comment by zincli** [comment]
@csbun 过来交流一下呗哈哈

**Comment by csbun** [comment]
业务/技术交流好啊，欢迎钉钉联系 @钗佬
